MTA-2696-lang .NET support
migtools/mta-documentation pull request #23
Opened 2024-07-26 07:47 UTC by vsodhi

### JIRA

* [MTA-2696](https://issues.redhat.com/browse/MTA-2696)

Support for .NET language added

### Preview

https://vsodhi.github.io/previews/MTA/MTA-2696.html#_rulesets

2024-07-26 09:38 UTC, rromannissen requested changes
I don't see any capabilities for the .NET provider being added in 2.2.3, nor any explanation of the .NET provider itself as the ones we have for the builtin, java and go providers right after the change that was included. This is not only not complete, it's not even started.

2024-07-26 11:49 UTC, dymurray commented on docs/topics/yaml-rule-structure-syntax.adoc
> +* `.NET`
this is `dotnet`

2024-08-09 08:35 UTC, vsodhi commented on docs/topics/yaml-rule-structure-syntax.adoc
> +* `.NET`
fixed.

2024-08-09 11:42 UTC, anarnold97 commented
@midays - please can you review. thanks

2024-08-12 19:41 UTC, dymurray approved these changes

2024-08-13 10:54 UTC, vsodhi commented on docs/topics/yaml-rule-structure-syntax.adoc
> +A provider detects the programming languages, frameworks, and tools used to build an application and creates default rulesets for each supported provider using the Language Server Protocol (LSP) acco
fixed.

2024-08-13 10:55 UTC, midays approved these changes
LGTM

2024-08-13 18:42 UTC, anarnold97 commented on docs/topics/yaml-rule-structure-syntax.adoc
> +[[tabl-Supported-providers-and-rule-conditions]]
```suggestion
[[table-Supported-providers-and-rule-conditions]]
```
Pedantic... very pedantic

2024-08-14 03:17 UTC, vsodhi commented on docs/topics/yaml-rule-structure-syntax.adoc
> +[[tabl-Supported-providers-and-rule-conditions]]
good catch. fixed.

2024-08-14 17:28 UTC, merged