[WIP] MTA-3367 RHSSO admin info
migtools/mta-documentation pull request #54
Opened 2024-09-10 13:12 UTC by vsodhi

JIRA: https://issues.redhat.com/browse/MTA-3367

2024-09-11 13:42 UTC, anarnold97 commented on docs/topics/mta-7-installing-web-console-on-openshift.adoc
> +Hat Single Sign-On] (RHSSO) instance for user authentication and authorization.
```suggestion
The {ProductShortName} uses link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.6[Red Hat Single Sign-On (RHSSO)] instance for user authentication and authorization.
```

2024-09-11 13:46 UTC, anarnold97 commented on docs/topics/mta-7-installing-web-console-on-openshift.adoc
> +To create a dedicated route for the RHSSO instance, set the `rhsso_external_access` parameter to `True` in the Tackle CR for {ProductShortName}.
```suggestion
To create a dedicated route for the RHSSO instance, set the `rhsso_external_access` parameter to `true` in the Tackle custom resource (CR) for {ProductShortName}.
```

2024-09-12 16:33 UTC, vsodhi commented on docs/topics/mta-7-installing-web-console-on-openshift.adoc
> +To create a dedicated route for the RHSSO instance, set the `rhsso_external_access` parameter to `True` in the Tackle CR for {ProductShortName}.
fixed.

2024-09-12 16:33 UTC, vsodhi commented on docs/topics/mta-7-installing-web-console-on-openshift.adoc
> +Hat Single Sign-On] (RHSSO) instance for user authentication and authorization.
fixed.

2024-09-16 18:20 UTC, rromannissen requested changes
Rewrite doesn't cover the requested changes.

2024-09-24 11:51 UTC, vsodhi commented
@rromannissen Based on our discussion, I've added the missing link under the "additional resources" subsection; please ack. Thank you!

2024-09-24 13:59 UTC, merged