Mta 4016 analyzer task rbac
migtools/mta-documentation pull request #73
Opened 2024-11-25 14:57 UTC by anarnold97

2024-11-25 15:56 UTC, anarnold97 commented
@mguetta - please can you have a look, as i am not sure what else to add to the snippet, or where else this should be added?
Thanks

2024-11-25 17:03 UTC, istein1 commented on docs/topics/analyzer-rbac-snippet.adoc
> +An analyzer task created by a user, can be canceled by any other user.
I suggest to remove the specific example of analyzer task access,
as we have the no multi-user access restriction on other resources as well.
Just leave the ".No multi-user access restrictions on resources" warning
and place it in the head of the MTA doc.

2024-11-25 18:55 UTC, mguetta1 requested changes
@anarnold97 thanks for this PR.
Could you please add this as a known issue rather than snippet?
And I am not sure about including this information in all the files here. From my point of view, I would like to see it as a known issue with the example that "An analyzer task created by a user, can be canceled by any other use" as a result

2024-11-25 21:07 UTC, anarnold97 commented
> @anarnold97 thanks for this PR. Could you please add this as a known issue rather than snippet? And I am not sure about including this information in all the files here. From my point of view, I would like to see it as a known issue with the example that "An analyzer task created by a user, can be canceled by any other use" as a result

@mguetta1 - i will add as a **Known Issue** in another PR, so we are not relying on the readers looking at the release notes. See - [MTA-4014: Custom rules in analysis Dependency rule is not fired](https://github.com/migtools/mta-documentation/pull/74)  

* [7.1.1 Known issues](https://anarnold97.github.io/MTA-Preview/MTA/MTA-4014.html#known-issues-7-1-1_release-notes)

* [7.1.0 Known issues](https://anarnold97.github.io/MTA-Preview/MTA/MTA-4014.html#known-issues-7-1-0_release-notes)

2024-12-05 15:05 UTC, dymurray approved these changes

2024-12-05 19:06 UTC, anarnold97 commented on docs/cli-guide/master.adoc
> +
```suggestion
```

2024-12-05 19:07 UTC, anarnold97 commented on docs/eclipse-code-ready-studio-guide/master.adoc
> +
```suggestion
```

2024-12-05 19:07 UTC, anarnold97 commented on docs/getting-started-guide/master.adoc
> +
```suggestion
```

2024-12-05 19:08 UTC, anarnold97 commented on docs/plugin-guide/master.adoc
> +
```suggestion
```

2024-12-05 19:09 UTC, anarnold97 commented on docs/intellij-idea-plugin-guide/master.adoc
> +
```suggestion
```

2024-12-05 19:09 UTC, anarnold97 commented on docs/rules-development-guide/master.adoc
> +
```suggestion
```

2024-12-05 19:09 UTC, anarnold97 commented on docs/vs-code-extension-guide/master.adoc
> +
```suggestion
```

2024-12-05 19:46 UTC, anarnold97 commented on docs/topics/analyzer-rbac-snippet.adoc
> +There are no multi-user access restrictions on resources.
```suggestion
There are no multi-user access restrictions on resources. For example, an analyzer task created by a user, can be canceled by any other user.
```

2024-12-05 19:54 UTC, anarnold97 commented on docs/topics/mta-web-configuring-and-running-an-application-analysis.adoc
> +
```suggestion
```

2024-12-06 13:38 UTC, istein1 commented
LGTM

2024-12-07 18:07 UTC, anarnold97 commented on docs/topics/analyzer-rbac-snippet.adoc
> +There are no multi-user access restrictions on resources. For example, an analyzer task created by a user, can be canceled by any other user.
```suggestion
There are no multi-user access restrictions on resources. For example, an analyzer task created by a user can be canceled by any other user.
```

2024-12-07 18:08 UTC, merged